### PR TITLE
WIP: Fix for Dynamic Assignment Bug

### LINKED ISSUE #1066: Dynamic assignment is broken
We updated to latest upstream branch main last week. Previously, with Dynamic on, we could post a link and folks could just jump in and start sending. Now, each person has to be assigned a batch and/or max count has to be updated manually from 0 to a number. cc: @deasterdaywfp

### PR DESCRIPTION
**Pull request by shakalee14**
WIP 
fixes #1066

### CODE REVIEW

**Comment by deasterdaywfp** [comment]
@joemcl @codygordon @lperson What can we do to address these errors upon check? Can we still address and merge the fix to run dynamic in the latest build again?

Also, thank you 1000% @shakalee14 !

**Review by bdatkins — DISMISSED** [review]

**Comment by deasterdaywfp** [comment]
Thank you @bdatkins !

**Review by deasterdaywfp — COMMENTED** [review]
@bdatkins is there anything that I need to do to approve changes? Shall we attempt the merge again and test?

File: src/components/AssignmentSummary.jsx [hunk 1]
```diff
@@ -117,7 +117,7 @@ export class AssignmentSummary extends Component {
               title: 'Send first texts',
               count: unmessagedCount,
               primary: true,
-              disabled: (useDynamicAssignment && !hasUnassignedContacts && unmessagedCount == 0) || (useDynamicAssignment && maxContacts === 0),
+              disabled: (useDynamicAssignment && !hasUnassignedContacts && unmessagedCount == 0 && maxContacts !== 0) ? true : false,
```
Comment (harpojaeger) [inline src/components/AssignmentSummary.jsx]: It might make sense to move this boolean logic to L14, before `this.renderBadgedButton` is called, so it can be described more clearly. Also, is the `? true : false` necessary here?

**Comment by joemcl** [comment]
Hey @deasterdaywfp - we can test this branch on our staging site to see if it works. But merging into upstream branch main requires @schuyler1d or Ann ( @mathemagica ) with MoveOn to review the code, it seems.

**Comment by deasterdaywfp** [comment]
Right thank you Joe, makes perfect sense. Thank you for that clarification.

**Review by schuyler1d — DISMISSED** [review]
:+1:

File: src/components/AssignmentSummary.jsx (hunk 1 above)
Comment (schuyler1d) [reply src/components/AssignmentSummary.jsx]: agree.  I also think the `&& maxContacts != 0` is maybe incorrect.  If maxContacts is not zero, it's still possible that it's disabled, right?  The logic might be a bit weirder....

Comment (shakalee14) [reply src/components/AssignmentSummary.jsx]: thanks for the feedback. i think this part doesnt need to be changed after doing further qa

**Review by schuyler1d — APPROVED** [review]
:+1:
