### PR TITLE
fixes role saving including fixes #239

### LINKED ISSUE #239: On people screen, superadmin cannot change a person's role
To reproduce:

1) Go to /admin/{orgId}/people
2) For any texter, click "Texter" and change the drop-down to "Admin"
3) The drop-down should now say "Admin" or give some indication that the change is being saved. Instead, it still says "Texter"

### PR DESCRIPTION
**Pull request by schuyler1d**

### CODE REVIEW

File: src/server/api/schema.js [hunk 1]
```diff
@@ -386,9 +386,10 @@ const rootMutations = {
       return newJob
     },
     editOrganizationRoles: async (_, { userId, organizationId, roles }, { user, loaders }) => {
-      const currentRoles = r.table('user_organization')
-        .getAll([organizationId, user.id], { index: 'organization_user' })
-        .pluck('role')('role')
+      const currentRoles = (await r.knex('user_organization')
+        .where({organization_id: organizationId,
+                user_id: userId}).select('role')).map((res) => (res.role))
+      console.log(currentRoles)
```
Comment (sreynen) [inline src/server/api/schema.js]: Assuming this `console.log` was for debugging, and isn't needed in prod code.

**Review by sreynen — APPROVED** [review]
Other than console.log, 👍
